#!/bin/bash


echo "ingrese valor (si es un directorio inicielo con /):"
read P

if [ -f "$p" ]; then

	bash $p

else
	echo si va a ejecutar un archivo le recomiendo 
	echo $ ./nombredelarchivo o bash nombre del archivo

fi  
